### ISSUE TITLE
Scene management

### ISSUE THREAD

**Issue by dirkroorda** [CLARIAH/pure3dx#10]
A scene belongs to an edition and may refer to several models in the same edition.

The scene file is called `voyager.svx.json`.

When users work in voyager-story they essentially edit this `.svx.json` file.
They can also create annotations, whose metadata end up in that json file.
But lengthier bodies of those annotations (articles) end up in an articles directory on the file system.
Including additional media files that those articles refer to.

We need controls to upload and delete scenes.
If we delete a scene, we should also give the option to delete the related files.

When have have deleted and uploaded scene files, the directory with articles and media may contain unreferenced files. We should give the user the option to review them and delete them, taking care that no files are deleted that are referenced from the latest scene.

**Comment by dirkroorda** [comment]
A better way to create scenes is coming up: the voyager standalone can use drag-and-drop by which the user can dump models (.glb, .gltf) and scenes (.svx.json) onto the interface and start annotating.

However, the result of these actions cannot be sent to the server from voyager standalone.
The user has to save them from the browser. 

We would like to have the drag/drop functionality of the standalone also working in the voyager store, so that we can offer the user a web-based scene creation facility, without the need for saving any files manually and then uploading them manually.

This is something to discuss with @gjcope .

**Comment by dirkroorda** [comment]
Done. When no scene is present, voyager story will be presented in standalone mode.
When the user is done with dragging and dropping, he can extract the result from the browser as a zip file.

Going back to the edition page, the user can then upload this zip file.

**Comment by gjcope** [comment]
@dirkroorda FYI we are actively working on a drag/drop option independent of Standalone mode.
